name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt, lint, mypy]
    env:
      TOXENV: ${{ toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [37, 38]
        django: [22, 30, 31]

    env:
      TOXENV: py${{ matrix.python }}-django${{ matrix.django }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
