name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tox:
    name: Run tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]
        django: [2.2, 3.0, 3.1]

    env:
      TOXENV: py${{ matrix.python }}-django${{ matrix.django }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
